// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Song is a single worship song stored locally.
 */
export class Song {
    /**
     * Creates a new Song instance.
     * @param {Partial<Song>} [$$source = {}] - The source object to create the Song.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("slug" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["slug"] = "";
        }
        if (!("lyric" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lyric"] = "";
        }
        if (!("chord" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chord"] = "";
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Song instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Song}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField5_0($$parsedSource["metadata"]);
        }
        return new Song(/** @type {Partial<Song>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
