// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Slide is one projection slide.
 */
export class Slide {
    /**
     * Creates a new Slide instance.
     * @param {Partial<Slide>} [$$source = {}] - The source object to create the Slide.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "lyric" | "pause"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("lines" in $$source)) {
            /**
             * lyric lines (max 2)
             * @member
             * @type {string[]}
             */
            this["lines"] = [];
        }
        if (!("number" in $$source)) {
            /**
             * verse number for bible slides
             * @member
             * @type {number}
             */
            this["number"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Slide instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Slide}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField1_0($$parsedSource["lines"]);
        }
        return new Slide(/** @type {Partial<Slide>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
