// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application struct. Its exported methods are exposed to the
 * frontend via Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as db$0 from "./internal/db/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as slides$0 from "./internal/slides/models.js";

/**
 * AddSong inserts a song into the local database (used by hybrid search in Fase 4).
 * @param {db$0.Song} s
 * @returns {$CancellablePromise<number>}
 */
export function AddSong(s) {
    return $Call.ByID(1247012205, s);
}

/**
 * Counts returns the number of stored songs and bible verses.
 * @returns {$CancellablePromise<{ [_ in string]?: number }>}
 */
export function Counts() {
    return $Call.ByID(128504237).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * FocusProjector brings the projector window to the front.
 * @returns {$CancellablePromise<void>}
 */
export function FocusProjector() {
    return $Call.ByID(461761077);
}

/**
 * GetBibleSlides fetches a chapter from the beeble API (live, TB) and builds
 * one slide per verse. Caching into the local DB lands in Fase 4.
 * @param {string} book
 * @param {number} chapter
 * @param {string} version
 * @returns {$CancellablePromise<slides$0.Slide[]>}
 */
export function GetBibleSlides(book, chapter, version) {
    return $Call.ByID(2540254509, book, chapter, version).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSongSlides loads a song from the local DB and splits it into lyric slides.
 * @param {number} id
 * @returns {$CancellablePromise<slides$0.Slide[]>}
 */
export function GetSongSlides(id) {
    return $Call.ByID(2798670272, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * IsProjectorFullscreen reports whether the projector window is fullscreen.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsProjectorFullscreen() {
    return $Call.ByID(2889851706);
}

/**
 * ListSongs returns the song library (title/lyric match when query != "").
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<db$0.Song[]>}
 */
export function ListSongs(query, limit) {
    return $Call.ByID(554409833, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SearchSongs queries the local library (title/lyric).
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<db$0.Song[]>}
 */
export function SearchSongs(query, limit) {
    return $Call.ByID(244841873, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ToggleProjectorFullscreen toggles the projector window fullscreen.
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleProjectorFullscreen() {
    return $Call.ByID(2655128218);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = slides$0.Slide.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = db$0.Song.createFrom;
const $$createType4 = $Create.Array($$createType3);
